//var x: float = 8.2 + 2.1 / 3.0;
//var x: float = 2.0;
//print(x);
////var y: float = 10.0/2.0;
////x = 2.0 + y;
////    print(x + 2.0);
//// x = 5.0;
////x = y * x;
////print(x);
//print(x = 2.0+2.0);
//print(x);
////var z: bool = false;
////var a: bool = x < y;
////print(z && a);

//var x: int = 5;
//var y: int = 2;
//var z: int = x + y;
//print(z / 3);

//var x: float = 5; generate x it as int and not float
var x: float = 5.3 / 2.0;
var y: float = 10.1;
print(x + 1.0 + y);
